#ifndef _DEFAULT_757602046
#define _DEFAULT_757602046
#include <bur/plctypes.h>
#include <bur/plc.h>

#ifdef __cplusplus 
extern "C" 
{
#endif
	#include <Runtime.h>
	#include <Operator.h>
	#include <astime.h>
	#include <DataObj.h>
	#include <AsMem.h>
	#include <AsArLog.h>
	#include <sys_lib.h>
	#include <AsArProf.h>
	#include <brsystem.h>
	#include <FileIO.h>
	#include <standard.h>
	#include <asrfbext.h>
	#include <AsICMP.h>
	#include <AsUSB.h>
	#include <visapi.h>
	#include <TRF_LIB.h>
	#include <AsIO.h>
	#include <AsIOMMan.h>
	#include <AsIODiag.h>
	#include <AsSem.h>
	#include <AsBrStr.h>
	#include <LoopConR.h>
	#include <Acp10par.h>
	#include <NcGlobal.h>
	#include <ModDiag.h>
	#include <AsIecCon.h>
	#include <Acp10man.h>
	#include <Acp10sim.h>
	#include <Acp10_MC.h>
	#include <Arnc0man.h>
	#include <Acp10sdc.h>
	#include <Arnc0mx.h>
#ifdef __cplusplus
};
#endif

#include <globalTYP.h>
#include <globalVAR.h>
#include <motionhandling/motionglobalTYP.h>
#include <motionhandling/motionglobalVAR.h>
#include <motionhandling/motionglobaldefinesVAR.h>
#include <motionhandling/motionglobalsizeVAR.h>
#include <motionhandling/systemhandling/systemTYP.h>
#include <motionhandling/systemhandling/systemVAR.h>
#include <motionhandling/cnchandling/cncTYP.h>
#include <motionhandling/cnchandling/cncVAR.h>
#include <motionhandling/axeshandling/axesTYP.h>
#include <motionhandling/axeshandling/axesVAR.h>
#include <motionhandling/jogging/jogglobalTYP.h>
#include <motionhandling/feedforward/optmotconfigVAR.h>
#include <motionhandling/optimizer/optimizerTYP.h>
#include <motionhandling/optimizer/optimizerVAR.h>
#include <hmihandling/hmiglobalTYP.h>
#include <hmihandling/hmiglobalVAR.h>
#include <hmihandling/hmihardkey/hmihardkeyglobalTYP.h>
#include <hmihandling/hmihardkey/hmihardkeyglobalVAR.h>
#include <hmihandling/hmikeyctrl/hmikeycontrolglobalTYP.h>
#include <hmihandling/hmikeyctrl/hmikeycontrolglobalVAR.h>
#include <hmihandling/hmimain/hmimainglobalTYP.h>
#include <hmihandling/hmimain/hmimainglobalVAR.h>
#include <hmihandling/hmisetup/hmisetupglobalTYP.h>
#include <hmihandling/hmisetup/hmisetupglobalVAR.h>
#include <hmihandling/hmiio/hmiioglobalTYP.h>
#include <hmihandling/hmiio/hmiioglobalVAR.h>
#include <hmihandling/hmiprg/hmiprogramglobalTYP.h>
#include <hmihandling/hmiprg/hmiprogramglobalVAR.h>
#include <hmihandling/hmieditor/hmieditorglobalTYP.h>
#include <hmihandling/hmieditor/hmieditorglobalVAR.h>
#include <hmihandling/hmialarm/hmialarmglobalTYP.h>
#include <hmihandling/hmialarm/hmialarmglobalVAR.h>
#include <hmihandling/hmijog/hmijogglobalTYP.h>
#include <hmihandling/hmijog/hmijogglobalVAR.h>
#include <errorhandling/errorTYP.h>
#include <errorhandling/errorVAR.h>
#include <recipe/recipeglobalTYP.h>
#include <recipe/recipeglobalVAR.h>
#include <userstd/globaluserstdVAR.h>
#endif
