(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Program: System
 * File: System.typ
 * Author: radaka
 * Created: February 18, 2009
 ********************************************************************
 * Local data types of program System
 ********************************************************************)

TYPE
	SystemModeChangeSteps_Type : 
		(
		SYSMODECHANGE_STOP_CNC,
		SYSMODECHANGE_W_STOP_CNC,
		SYSMODECHANGE_STOP_AXES,
		SYSMODECHANGE_W_STOP_AXES,
		SYSMODECHANGE_HOME_AUTOPOS,
		SYSMODECHANGE_W_HOME_AUTOPOS,
		SYSMODECHANGE_MOVE_AUTOPOS,
		SYSMODECHANGE_W_MOVE_AUTOPOS,
		SYSMODECHANGE_MOVEHOME_AUTOPOS,
		SYSMODECHANGE_W_MOVEHOME_AUTOPOS,
		SYSMODECHANGE_CYCLIC_POSITION,
		SYSMODECHANGE_W_CYCLIC_POSITION,
		SYSMODECHANGE_RESET_JOLT_TIME,
		SYSMODECHANGE_W_RESET_JOLT_TIME,
		SYSMODECHANGE_SET_MODE
		);
	SystemStateSteps_Type : 
		(
		SYSSTATESTEP_BOOTING,
		SYSSTATESTEP_DISABLED,
		SYSSTATESTEP_STANDBY,
		SYSSTATESTEP_ACTIVE,
		SYSSTATESTEP_HOMING,
		SYSSTATESTEP_STOPPING,
		SYSSTATESTEP_ERRORSTOP,
		SYSSTATESTEP_SERVICE
		);
	SystemTimeoutSteps_Type : 
		(
		SYSTIMEOUTSTEP_CHECK,
		SYSTIMEOUTSTEP_ERROR,
		SYSTIMEOUTSTEP_FINISHED
		);
	SystemActionSteps_Type : 
		(
		SYSACTIONSTEP_COMMAND,
		SYSACTIONSTEP_ENABLE_PWR_AXES,
		SYSACTIONSTEP_W_ENABLE_PWR_AXES,
		SYSACTIONSTEP_ENABLE_AXES,
		SYSACTIONSTEP_W_ENABLE_AXES,
		SYSACTIONSTEP_ENABLE_CNC,
		SYSACTIONSTEP_W_ENABLE_CNC,
		SYSACTIONSTEP_ESTOP_CNC,
		SYSACTIONSTEP_W_ESTOP_CNC,
		SYSACTIONSTEP_ESTOP_AXES,
		SYSACTIONSTEP_W_ESTOP_AXES,
		SYSACTIONSTEP_DISABLE_AXES_CNC,
		SYSACTIONSTEP_W_DISABLE_AXES_CNC,
		SYSACTIONSTEP_DISABLE_PWR_AXES,
		SYSACTIONSTEP_HOMING,
		SYSACTIONSTEP_W_HOMING,
		SYSACTIONSTEP_STOPPING_CNC,
		SYSACTIONSTEP_W_STOPPING_CNC,
		SYSACTIONSTEP_STOPPING_AXES,
		SYSACTIONSTEP_W_STOPPING_AXES,
		SYSACTIONSTEP_RESET,
		SYSACTIONSTEP_W_RESET,
		SYSACTIONSTEP_ACKNOWLEDGE,
		SYSACTIONSTEP_INIT,
		SYSACTIONSTEP_W_INIT,
		SYSACTIONSTEP_START_SIMULATION,
		SYSACTIONSTEP_W_START_SIMULATION,
		SYSACTIONSTEP_STOP_SIMULATION,
		SYSACTIONSTEP_W_STOP_SIMULATION
		);
	SystemAction_Type : 
		(
		SYSACTION_NO_ACTION,
		SYSACTION_ENABLE,
		SYSACTION_EMERGENCYSTOP,
		SYSACTION_HOME,
		SYSACTION_CHANGEMODE,
		SYSACTION_STOP,
		SYSACTION_RESET,
		SYSACTION_ACKNOWLEDGE,
		SYSACTION_INIT,
		SYSACTION_START_SIMULATION,
		SYSACTION_STOP_SIMULATION
		);
	SystemSpindleHandling_Type : 	STRUCT 
		Velocity : REAL;
		ChangeSpeed : BOOL;
		Stop : BOOL;
		Anticlockwise : BOOL;
	END_STRUCT;
	SystemPrivate_Type : 	STRUCT 
		SystemStateStep : SystemStateSteps_Type;
		AccessOk : BOOL;
		TimeoutTimer : UDINT;
		TimeoutStep : SystemTimeoutSteps_Type;
		StartupOk : BOOL;
		ActionStep : SystemActionSteps_Type;
		ActionRequest : SystemAction_Type;
		ActionResponse : SystemAction_Type;
		WasEnable : BOOL;
		Disabeling : BOOL;
		Enabeling : BOOL;
		Resetting : BOOL;
		ErrorStopping : BOOL;
		ModeChangeStep : SystemModeChangeSteps_Type;
		ModeChanging : BOOL;
		SpindleHandling : ARRAY[0..3] OF SystemSpindleHandling_Type;
		HomeOrderIndex : USINT;
		HomeFromActive : BOOL;
		OldMode : USINT;
		TempControllerOnStatus : BOOL;
	END_STRUCT;
END_TYPE
