/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _LIBRARIES_20150625092502_
#define _LIBRARIES_20150625092502_

__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asrfbext/asrfbext.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/TRF_LIB/TRF_LIB.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/Ncglobal.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HmiHandling/HmiIO/ModDiag/ModDiag.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10man/Acp10man.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Arnc0man/arnc0man.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sdc/acp10sdc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Arnc0mx/arnc0mx.typ\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Operator/operator.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/standard/standard.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/asrfbext/asrfbext.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsICMP/AsICMP.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/TRF_LIB/TRF_LIB.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIO/AsIO.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOMMan/AsIOMMan.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsSem/AsSem.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsBrStr/AsBrStr.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/Ncglobal.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HmiHandling/HmiIO/ModDiag/ModDiag.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIecCon/AsIecCon.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Arnc0mx/arnc0mx.fun\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Runtime/runtime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/astime/astime.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/DataObj/DataObj.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsMem/AsMem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArLog/AsArLog.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/sys_lib/sys_lib.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsArProf/AsArProf.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/brsystem/brsystem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/FileIO/FileIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsICMP/AsICMP.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsUSB/AsUSB.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/visapi/Visapi.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/TRF_LIB/TRF_LIB.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIO/AsIO.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIOMMan/AsIOMMan.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsIODiag/AsIODiag.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/AsSem/AsSem.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/LoopConR/LoopConR.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10par/Acp10par.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/NcGlobal/Ncglobal.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/HmiHandling/HmiIO/ModDiag/ModDiag.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sdc/acp10sdc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10sim/acp10sim.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Acp10_MC/acp10_mc.var\\\" scope \\\"global\\\"\\n\"");
__asm__(".ascii \"iecfile \\\"Logical/Libraries/Arnc0mx/arnc0mx.var\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */
#ifdef _RUNTIME_EXPORT
	__asm__(".ascii\"plcexport \\\"r_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"f_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"rf_trig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetTime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SFCActionControl\\\" FUB\\n\"");
#endif
#ifdef _OPERATOR_EXPORT
	__asm__(".ascii\"plcexport \\\"SIZEOF\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ADR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SHR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ROR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ROL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SHL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AND\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"XOR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"OR\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"NOT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ADD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MUL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SUB\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIV\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MOVE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MAX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LIMIT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SEL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MUX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"GE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EQ\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"GT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"NE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ABS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SQRT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LOG\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EXP\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"COS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TAN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ASIN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ACOS\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ATAN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"EXPT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRUNC\\\" FUN\\n\"");
#endif
#ifdef _ASTIME_EXPORT
	__asm__(".ascii\"plcexport \\\"DTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"clock_ms\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureGetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructureExSetTime\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDT_TO_LocalDTStructure\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LocalDT_TO_UtcDTStructure\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UtcDTStructure_TO_LocalDT\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LocalDTStructure_TO_UtcDT\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ascTIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascDTStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ascDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIMEStructure_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_TIMEStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DTStructure_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DTStructure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DiffT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DiffDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TimeDeviceGetInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DstGetInfo\\\" FUB\\n\"");
#endif
#ifdef _DATAOBJ_EXPORT
	__asm__(".ascii\"plcexport \\\"DatObjCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjMove\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjChangeDate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjAttach\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DatObjDetach\\\" FUB\\n\"");
#endif
#ifdef _ASMEM_EXPORT
	__asm__(".ascii\"plcexport \\\"AsMemPartCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartDestroy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartAlloc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartAllocClear\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartRealloc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartFree\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsMemPartInfo\\\" FUB\\n\"");
#endif
#ifdef _ASARLOG_EXPORT
	__asm__(".ascii\"plcexport \\\"AsArLogCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogClear\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsArLogGetInfo\\\" FUB\\n\"");
#endif
#ifdef _SYS_LIB_EXPORT
	__asm__(".ascii\"plcexport \\\"Byte2Bit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"Bit2Byte\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"KEY_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"KEY_enadis\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_fix\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_copy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_store\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_burn\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_delete\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_write\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DA_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_clr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_chr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DIS_str\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxfatal\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_read\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxread\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_fatal\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERR_warning\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ERRxwarning\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_release\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_attach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_delete\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SM_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIM_ticks\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIM_musec\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SW_settime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SW_gettime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RTC_settime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RTC_gettime\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TMP_free\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TMP_alloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MEM_free\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MEM_alloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_release\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_attach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_cancel\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"AVT_create\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_sleep\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_exit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_freemsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_recmsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_sendmsg\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UT_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_name\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_allsuspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_tmp_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_tmp_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_resume\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_suspend\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ST_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"FORCE_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_ver\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_list\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MO_info\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SYS_battery\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYSreset\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYSxinfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SYS_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xlist\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_ninfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_item\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_ident\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_list\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_info\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xgetval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xsetval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_xgetadr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_getadr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_getval\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"PV_setval\\\" FUN\\n\"");
#endif
#ifdef _ASARPROF_EXPORT
	__asm__(".ascii\"plcexport \\\"LogInstall\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogDeInstall\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStateGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogArchInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStart\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogEvent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LogIdleShow\\\" FUB\\n\"");
#endif
#ifdef _BRSYSTEM_EXPORT
	__asm__(".ascii\"plcexport \\\"MEMInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MEMxInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"RTInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TARGETInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"HWInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysconfInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SysconfSet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"BatteryInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"EXCInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"ZYKVLenable\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemPut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"PMemSize\\\" FUB\\n\"");
#endif
#ifdef _FILEIO_EXPORT
	__asm__(".ascii\"plcexport \\\"FileCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileReadEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileWriteEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileRename\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileTruncate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirOpen\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirClose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirReadEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirRename\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirCopy\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DirDeleteEx\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SetAttributes\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"GetAttributes\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevMemInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevLink\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DevUnlink\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"FileIoGetSysError\\\" FUN\\n\"");
#endif
#ifdef _STANDARD_EXPORT
	__asm__(".ascii\"plcexport \\\"RF_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTUD\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTD\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"CTU\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"F_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"R_TRIG\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SR\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"RS\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SEMA\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TON\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TOF\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TP\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TON_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TOF_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"TP_10ms\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LEN\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LEFT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RIGHT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MID\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"CONCAT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INSERT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DELETE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REPLACE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"FIND\\\" FUN\\n\"");
#endif
#ifdef _ASRFBEXT_EXPORT
	__asm__(".ascii\"plcexport \\\"RfbExtInit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtConnect\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtSetClientCaption\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtSetPassword\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtKeyState\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtReconnect\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtStartProcess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtProcessState\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtNrClientsConnected\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtServerTimeout\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtDisableClientLogin\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtDisconnectAllClients\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtEnableClientLogin\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtSetMaxClients\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtDataAge\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtJoystickValue\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtResetHandwheelValue\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtHandwheelValue\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"RfbExtPotiValue\\\" FUN\\n\"");
#endif
#ifdef _ASICMP_EXPORT
	__asm__(".ascii\"plcexport \\\"IcmpPing\\\" FUB\\n\"");
#endif
#ifdef _ASUSB_EXPORT
	__asm__(".ascii\"plcexport \\\"UsbNodeListGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UsbNodeGet\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"UsbDescriptorGet\\\" FUB\\n\"");
#endif
#ifdef _VISAPI_EXPORT
	__asm__(".ascii\"plcexport \\\"VA_Attach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_BlitBitmap\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Configure\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_CopyScreenRect\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_DelAlarmHistory\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetActiveAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetAlarmCount\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Detach\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_DrawBitmap\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Ellipse\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_ExchangeFont\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_ExtractKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_FreeBitmap\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetAlarmList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetBrightness\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetContrast\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetDisplayInfo\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetKeyMatrix\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetPanelStatus\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetTouchAction\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_LangIsAvailable\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Line\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_LoadBitmap\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_NGetAlCurPos\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_NGetCalStatus\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_NGetContrast\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_NGetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Quit\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_QuitAlarms\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Rect\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Redraw\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Saccess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SaveSettings\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetBacklight\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetBrightness\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetClipRegion\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetContrast\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetPaletteColor\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetUserParam\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Setup\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetupX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Shutdown\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Srelease\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_StartProject\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_StartVisuByName\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_StartTouchCal\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_StopProject\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_Textout\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_TimeSynchronize\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_wcAlarmGetList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_wcGetActAlarmList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_wcGetExAlarmList\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_wcGetTextByTextGroup\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_wcTextout\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetActualLang\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_ClearTouchEventBuffer\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_RegisterClient\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_StartProcess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_TerminateProcess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_GetProcessExitCode\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetProcessZOrder\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_SetVisualizationZOrder\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"VA_RunJScript\\\" FUN\\n\"");
#endif
#ifdef _TRF_LIB_EXPORT
	__asm__(".ascii\"plcexport \\\"TRF_init_instance\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_generic\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_direct\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_direct2\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_inverse\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_inverse2\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_get_joints_pos\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_get_size\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_get_mode\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_direct3\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TRF_inverse3\\\" FUN\\n\"");
#endif
#ifdef _ASIO_EXPORT
	__asm__(".ascii\"plcexport \\\"AsIODPStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOSetForceValue\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOEnableForcing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIODisableForcing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOGlobalDisableForcing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOFListDP\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOListDP\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOPVInfo\\\" FUB\\n\"");
#endif
#ifdef _ASIOMMAN_EXPORT
	__asm__(".ascii\"plcexport \\\"AsIOMMCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOMMRemove\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"AsIOMMCopy\\\" FUB\\n\"");
#endif
#ifdef _ASIODIAG_EXPORT
	__asm__(".ascii\"plcexport \\\"DiagCreateInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DiagDisposeInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DiagGetNumInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"DiagGetStrInfo\\\" FUB\\n\"");
#endif
#ifdef _ASSEM_EXPORT
	__asm__(".ascii\"plcexport \\\"SemCreate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SemDelete\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SemGetInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"SemAcquire\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SemRelease\\\" FUN\\n\"");
#endif
#ifdef _ASBRSTR_EXPORT
	__asm__(".ascii\"plcexport \\\"brsftoa\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsatof\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsitoa\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsatoi\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemset\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemcpy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemmove\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsmemcmp\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcat\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrlen\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcpy\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"brsstrcmp\\\" FUN\\n\"");
#endif
#ifdef _LOOPCONR_EXPORT
	__asm__(".ascii\"plcexport \\\"LCRPID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRScal\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRCurveByPoints\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPIDpara\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRContinServo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPT1\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRRamp\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRIntegrate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRLimit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRLimScal\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPWM\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRMovAvgFlt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRTimeBasedOnOff\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRDifferentiate\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRSlimPID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPIDTune\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPFM\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRSimModExt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRTt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPT2\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPT1e\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRDblActPID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRMinMax\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRTempPID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRTempTune\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRPT2o\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"LCRSchedulePWM\\\" FUB\\n\"");
#endif
#ifdef _NCGLOBAL_EXPORT
	__asm__(".ascii\"plcexport \\\"nccnccom\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_dir\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_inf\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_id\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_wr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncda_cr\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncaccess\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncalloc\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncaction\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"ncglobal_action\\\" FUN\\n\"");
#endif
#ifdef _MODDIAG_EXPORT
	__asm__(".ascii\"plcexport \\\"ModuleDiagnose\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"IOStatus\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"IOList\\\" FUN\\n\"");
#endif
#ifdef _ASIECCON_EXPORT
	__asm__(".ascii\"plcexport \\\"swapDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"swapDWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"N_TO_HINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NTIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NTOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NLREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NUDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NUINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"H_TO_NINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BOOL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"BYTE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DWORD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"SINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"INT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"USINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"UDINT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TIME_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DT_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"DATE_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"TOD_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"REAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_STRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"LREAL_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"STRING_TO_WSTRING\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_BOOL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_BYTE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_WORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DWORD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_SINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_INT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_USINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_UINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_UDINT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_TIME\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DT\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_DATE\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_TOD\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_REAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_LREAL\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"WSTRING_TO_STRING\\\" FUN\\n\"");
#endif
#ifdef _ACP10_MC_EXPORT
	__asm__(".ascii\"plcexport \\\"MC_AbortTrigger\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutCommand\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AutoCamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_AxisErrorCollector\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_BrakeControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_BrakeOperation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcCamFromPoints\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcCamFromSections\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcPointsFromCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CalcSectionsFromCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CamTransition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CheckAutCompensation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CheckEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CommandError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ConfigPowerStageCheck\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CrossCutterControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicReadDataInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_CyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadCamProfileData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_DownloadParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_EventMoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GearIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetCamMasterPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetCamSlavePosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetErrorText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetHardwareInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetParIDTransferInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_HomeAcpEncoder\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutEvent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAutState\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitAxisSubjectPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitCyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitCyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitEndlessPosAcpEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitMasterParIDTransfer\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitModPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParList\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveNetworkData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveNetworkEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitReceiveParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_InitSendParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogLimitPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_JogTargetPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LimitLoadCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_LoadAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveAbsoluteTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveAdditiveTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicPositionExt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveCyclicVelocityExt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_MoveVelocityTriggStop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_NetTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_NetworkInit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Offset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_OffsetVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_OffsetZone\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_GetParIDInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ParTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ParTraceConfig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Phasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_PowerMeter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadAutPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadCyclicPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadDriveStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadNetTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReadParTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ReceiveParIDOnPLC\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_ResetAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SaveAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SaveCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetHardwareInputs\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupController\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupFromParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupInductionMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupIsqRipple\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupMotorPhasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_SetupSynchronMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_Simulation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_VelocityControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_WriteParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_WriteParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamOut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_CamTableSelect\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearInPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_GearOut\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Halt\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Home\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_MoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Phasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Power\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualTorque\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_ReadStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Reset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_SetOverride\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_Stop\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_BR_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteBoolParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_WriteParameter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_001_ReadActualVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_002_ReadActualTorque\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_003_GearInPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_004BR_BrakeOperation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_005BR_MoveAbsoluteTriggSto\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_006BR_MoveAdditiveTriggSto\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_007BR_MoveVelocityTriggSto\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_008BR_ReadParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_009BR_WriteParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_010BR_InitCyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_011BR_InitCyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_012BR_InitParList\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_013BR_InitParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_014BR_DownloadCamProfileOb\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_015BR_DownloadParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_016BR_InitParSequ\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_017BR_InitAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_018BR_InitAutState\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_019BR_InitAutEvent\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_020BR_AutControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_021_ReadDigitalInput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_022_ReadDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_023_WriteDigitalOutput\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_024BR_InitMasterParIDTrans\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_025BR_InitModPos\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_026BR_DownloadCamProfileDa\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_027BR_InitAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_028BR_SaveAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_029BR_LoadAxisPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_030BR_InitAxisSubjectPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_031BR_TouchProbe\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_032BR_Offset\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_033BR_Phasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_034BR_EventMoveAbsolute\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_035BR_EventMoveAdditive\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_036BR_EventMoveVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_037BR_CamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_038BR_AutoCamDwell\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_039BR_HomeAcpEncoder\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_040BR_CyclicRead\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_041BR_CyclicWrite\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_042BR_Simulation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_043BR_ReadDriveStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_044BR_CalcCamFromSections\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_046BR_ReadAutPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_047BR_InitAutData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_048BR_GetErrorText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_049BR_NetTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_050BR_ReadNetTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_051BR_ParTrace\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_052BR_ReadParTraceStatus\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_053BR_InitEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_056BR_GetCamSlavePosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_057BR_GetCamMasterPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_058BR_SetupInductionMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_059BR_SetupController\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_060BR_PowerMeter\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_061BR_ReadParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_062BR_WriteParIDText\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_064BR_SetupMotorPhasing\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_065BR_CyclicReadDataInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_066BR_AutCommand\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_068BR_SetupIsqRipple\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_069BR_ParTraceConfig\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_070BR_CheckAutCompensation\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_071BR_TorqueControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_072BR_AxisErrorCollector\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_073BR_ReadAxisError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_074BR_DigitalCamSwitch\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_075BR_GetParIDInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_076BR_SetHardwareInputs\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_077BR_BrakeControl\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_078BR_InitSendParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_079BR_InitReceiveParID\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_080BR_CalcSectionsFromCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_081BR_InitReceiveNetworkData\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_082BR_SaveCamProfileObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_083BR_JogVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_084BR_JogLimitPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_085BR_JogTargetPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_086BR_GetParIDTransferInfo\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_087BR_GearIn\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_088BR_OffsetVelocity\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_089BR_OffsetZone\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_090BR_SetupSynchronMotor\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_091BR_CheckEndlessPosition\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_092BR_LimitLoad\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_093BR_LimitLoadCam\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_095BR_ConfigPowerStageCheck\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_094BR_ResetAutPar\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_096BR_InitEndlessPosAcpEnc\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_097BR_NetworkInit\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_098BR_CommandError\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_099BR_SetupFromParTabObj\\\" FUB\\n\"");
	__asm__(".ascii\"plcexport \\\"MC_100BR_CamIn\\\" FUB\\n\"");
#endif
#ifdef _ARNC0MX_EXPORT
	__asm__(".ascii\"plcexport \\\"MXPointToJointEx1\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXPointToJointEx\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXJointToPointEx1\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXJointToPointEx\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXCncAxesToPoint\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFromOrient\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXToOrient\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXConvertOrient\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameRotX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameRotY\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameRotZ\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameEuler\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameRPY\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameTrans\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameTransX\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameTransY\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameTransZ\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFrameApply\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXFromFrame\\\" FUN\\n\"");
	__asm__(".ascii\"plcexport \\\"MXToFrame\\\" FUN\\n\"");
#endif

__asm__(".previous");


#endif /* _LIBRARIES_20150625092502_ */

