/* Automation Studio generated header file */
/* Do not edit ! */

#ifndef _BUR_1479044160_23_
#define _BUR_1479044160_23_

#include <bur/plctypes.h>

/* Constants */
#ifdef _REPLACE_CONST
 #define WARNING_TIMEACTIVE 3000
 #define JOG_MODE_DIRECT 3U
 #define JOG_MODE_TOOL 2U
 #define JOG_MODE_BASE 1U
 #define JOG_MODE_JOINT 0U
 #define SYSTEM_STATUS_WARNING 5U
 #define SYSTEM_STATUS_SELECTRUNNING 3U
 #define SYSTEM_STATUS_SELECTED 1U
 #define SYSTEM_STATUS_RUNNING 2U
 #define SYSTEM_STATUS_PROGRAMHALT 4U
 #define SYSTEM_STATUS_NOACTIVE 0U
 #define SCALE_UNITS_INDEX_2 0.01f
 #define SCALE_UNITS_INDEX_1 0.1f
 #define SCALE_UNITS_INDEX_0 1.0f
 #define SCALE_STATUS_NOACTIVE 0
 #define SCALE_STATUS_ACIVE 1
 #define MODE_SINGLESTEP 3U
 #define MODE_SIMULATION 6U
 #define MODE_NOMODE 254U
 #define MODE_MOTION_JOG 0U
 #define MODE_MOTION_AUTO 1U
 #define MODE_MDI 1U
 #define MODE_HOME 5U
 #define MODE_DRYRUN 4U
 #define MODE_AUTOMATIC 0U
 #define MFUNCTION_WARNING 4U
 #define MFUNCTION_TIMEPRESSED 2000
 #define MFUNCTION_STANDBYRUNNING 1U
 #define MFUNCTION_STANDBY 0U
 #define MFUNCTION_SPINDLE 3U
 #define MFUNCTION_RUNNING 3U
 #define MFUNCTION_DISABLE 2U
 #define MFUNCTION_COOLING 1U
 #define MFUNCTION_M17 17U
 #define MFUNCTION_M16 16U
 #define MFUNCTION_M15 15U
 #define MFUNCTION_M14 14U
 #define MFUNCTION_M13 13U
 #define MFUNCTION_M12 12U
 #define MFUNCTION_M11 11U
 #define MFUNCTION_M10 10U
 #define HMIKEYCONTROL_STOPSINGLE 236U
 #define HMIKEYCONTROL_STOPSIMUL 235U
 #define HMIKEYCONTROL_STOPMDI 234U
 #define HMIKEYCONTROL_STOPJOG 233U
 #define HMIKEYCONTROL_STOPHOME 232U
 #define HMIKEYCONTROL_STOPDRYRUN 231U
 #define HMIKEYCONTROL_STOPAUTO 230U
 #define HMIKEYCONTROL_START 220U
 #define HMIKEYCONTROL_SELECTSYSTEM 110U
 #define HMIKEYCONTROL_SELECTSCALE 140U
 #define HMIKEYCONTROL_SELECTFUNCTIONM 130U
 #define HMIKEYCONTROL_SELECTAXIS 120U
 #define HMIKEYCONTROL_INIT 0U
 #define HMIKEYCONTROL_IDLE 100U
 #define HMIKEYCONTROL_CHANGEMODESINGLE 180U
 #define HMIKEYCONTROL_CHANGEMODESIMUL 210U
 #define HMIKEYCONTROL_CHANGEMODEMDI 160U
 #define HMIKEYCONTROL_CHANGEMODEJOG 170U
 #define HMIKEYCONTROL_CHANGEMODEHOME 200U
 #define HMIKEYCONTROL_CHANGEMODEDRYRUN 190U
 #define HMIKEYCONTROL_CHANGEMODEAUTO 150U
 #define HANDWHEEL_STATUS_NOACTIVE 0U
 #define HANDWHEEL_STATUS_HALT 2U
 #define HANDWHEEL_STATUS_ACTIVE 1U
 #define AXIS_STATUS_WARNING 3U
 #define AXIS_STATUS_NOACTIVE 0U
 #define AXIS_STATUS_FORWARD 1U
 #define AXIS_STATUS_BACKWARD 2U
#else
 _GLOBAL_CONST plctime WARNING_TIMEACTIVE;
 _GLOBAL_CONST unsigned char JOG_MODE_DIRECT;
 _GLOBAL_CONST unsigned char JOG_MODE_TOOL;
 _GLOBAL_CONST unsigned char JOG_MODE_BASE;
 _GLOBAL_CONST unsigned char JOG_MODE_JOINT;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_WARNING;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_SELECTRUNNING;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_SELECTED;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_RUNNING;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_PROGRAMHALT;
 _GLOBAL_CONST unsigned char SYSTEM_STATUS_NOACTIVE;
 _GLOBAL_CONST float SCALE_UNITS_INDEX_2;
 _GLOBAL_CONST float SCALE_UNITS_INDEX_1;
 _GLOBAL_CONST float SCALE_UNITS_INDEX_0;
 _GLOBAL_CONST plcbit SCALE_STATUS_NOACTIVE;
 _GLOBAL_CONST plcbit SCALE_STATUS_ACIVE;
 _GLOBAL_CONST unsigned char MODE_SINGLESTEP;
 _GLOBAL_CONST unsigned char MODE_SIMULATION;
 _GLOBAL_CONST unsigned char MODE_NOMODE;
 _GLOBAL_CONST unsigned char MODE_MOTION_JOG;
 _GLOBAL_CONST unsigned char MODE_MOTION_AUTO;
 _GLOBAL_CONST unsigned char MODE_MDI;
 _GLOBAL_CONST unsigned char MODE_HOME;
 _GLOBAL_CONST unsigned char MODE_DRYRUN;
 _GLOBAL_CONST unsigned char MODE_AUTOMATIC;
 _GLOBAL_CONST unsigned char MFUNCTION_WARNING;
 _GLOBAL_CONST plctime MFUNCTION_TIMEPRESSED;
 _GLOBAL_CONST unsigned char MFUNCTION_STANDBYRUNNING;
 _GLOBAL_CONST unsigned char MFUNCTION_STANDBY;
 _GLOBAL_CONST unsigned char MFUNCTION_SPINDLE;
 _GLOBAL_CONST unsigned char MFUNCTION_RUNNING;
 _GLOBAL_CONST unsigned char MFUNCTION_DISABLE;
 _GLOBAL_CONST unsigned char MFUNCTION_COOLING;
 _GLOBAL_CONST unsigned char MFUNCTION_M17;
 _GLOBAL_CONST unsigned char MFUNCTION_M16;
 _GLOBAL_CONST unsigned char MFUNCTION_M15;
 _GLOBAL_CONST unsigned char MFUNCTION_M14;
 _GLOBAL_CONST unsigned char MFUNCTION_M13;
 _GLOBAL_CONST unsigned char MFUNCTION_M12;
 _GLOBAL_CONST unsigned char MFUNCTION_M11;
 _GLOBAL_CONST unsigned char MFUNCTION_M10;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPSINGLE;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPSIMUL;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPMDI;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPJOG;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPHOME;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPDRYRUN;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_STOPAUTO;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_START;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_SELECTSYSTEM;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_SELECTSCALE;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_SELECTFUNCTIONM;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_SELECTAXIS;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_INIT;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_IDLE;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODESINGLE;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODESIMUL;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODEMDI;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODEJOG;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODEHOME;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODEDRYRUN;
 _GLOBAL_CONST unsigned short HMIKEYCONTROL_CHANGEMODEAUTO;
 _GLOBAL_CONST unsigned char HANDWHEEL_STATUS_NOACTIVE;
 _GLOBAL_CONST unsigned char HANDWHEEL_STATUS_HALT;
 _GLOBAL_CONST unsigned char HANDWHEEL_STATUS_ACTIVE;
 _GLOBAL_CONST unsigned char AXIS_STATUS_WARNING;
 _GLOBAL_CONST unsigned char AXIS_STATUS_NOACTIVE;
 _GLOBAL_CONST unsigned char AXIS_STATUS_FORWARD;
 _GLOBAL_CONST unsigned char AXIS_STATUS_BACKWARD;
#endif


/* Variables */
_GLOBAL struct HmiKeyControl_Type HmiKeyControl;





__asm__(".section \".plc\"");

/* Used IEC files */
__asm__(".ascii \"iecfile \\\"Logical/HmiHandling/HmiKeyCtrl/HmiKeyControlGlobal.var\\\" scope \\\"global\\\"\\n\"");

/* Exported library functions and function blocks */

__asm__(".previous");


#endif /* _BUR_1479044160_23_ */

