(********************************************************************
 * COPYRIGHT -- Bernecker + Rainer
 ********************************************************************
 * Program: Cnc
 * File: Cnc.typ
 * Author: radaka
 * Created: February 16, 2009
 ********************************************************************
 * Local data types of program Cnc
 ********************************************************************)

TYPE
	CncDryRunSteps_Type : 
		(
		CNCDRYRUN_START,
		CNCDRYRUN_WAIT_PROGRAM_START,
		CNCDRYRUN_WAIT_STOP_FOR_RESET,
		CNCDRYRUN_M1_WAIT_WHEEL_CHANGE,
		CNCDRYRUN_M1_WAIT_POSITIONING,
		CNCDRYRUN_M2_POSITION_CONTROL
		);
	CncPrivateDryRun_Type : 	STRUCT 
		ActualDryRunWheelPosition : REAL;
		OldDryRunWheelPosition : REAL;
		ActualPathPosition : REAL;
		DryRunWheelFactor : REAL;
		DryRunWheelFactorOld : REAL;
		WheelStartOffset : REAL;
		CalcDryRunWheelPosition : REAL;
		CalcDryRunWheelPositionOld : REAL;
		Step : CncDryRunSteps_Type;
		Override : REAL;
		CalcOverride : INT;
		Override_P_Factor : REAL;
		TimeoutTon : TON;
	END_STRUCT;
	CncStateSteps_Type : 
		(
		CNCSTATESTEP_DISABLED,
		CNCSTATESTEP_STANDBY,
		CNCSTATESTEP_MOVING,
		CNCSTATESTEP_STOPPING,
		CNCSTATESTEP_ERRORSTOP
		);
	CncPrivate_Type : 	STRUCT 
		StateStep : CncStateSteps_Type;
		ActionStep : CncActionSteps_Type;
		ActionRequest : CncAction_Type;
		ActionResponse : CncAction_Type;
		ActionStatus : UINT;
		AccessOk : BOOL;
		AccessStatus : UINT;
		CncDatAddress : UDINT;
		NetInitOk : BOOL;
		ErrorStopping : BOOL;
		Resetting : BOOL;
		WasEnable : BOOL;
		Enabeling : BOOL;
		NcCncComStatus : UINT;
		NcCncComOk : BOOL;
		Number : USINT;
		DryRun : CncPrivateDryRun_Type;
		DryrunActive : BOOL;
	END_STRUCT;
	CncActionSteps_Type : 
		(
		CNCACTIONSTEP_COMMAND,
		CNCACTIONSTEP_GLOBAL_INIT,
		CNCACTIONSTEP_W_GLOBAL_INIT,
		CNCACTIONSTEP_SET_WARNINGS,
		CNCACTIONSTEP_W_SET_WARNINGS,
		CNCACTIONSTEP_START_NCPROGRAM,
		CNCACTIONSTEP_W_START_NCPROGRAM,
		CNCACTIONSTEP_START_NCBLOCK,
		CNCACTIONSTEP_W_START_NCBLOCK,
		CNCACTIONSTEP_HALT,
		CNCACTIONSTEP_W_HALT,
		CNCACTIONSTEP_CONTINUE,
		CNCACTIONSTEP_W_CONTINUE,
		CNCACTIONSTEP_STOP,
		CNCACTIONSTEP_W_STOP,
		CNCACTIONSTEP_EMERGENCYSTOP,
		CNCACTIONSTEP_W_EMERGENCYSTOP,
		CNCACTIONSTEP_ERROR_TEXT,
		CNCACTIONSTEP_ERROR_ACKNOWLEDGE,
		CNCACTIONSTEP_ERROR_CHECK,
		CNCACTIONSTEP_LOAD_PARAMTER,
		CNCACTIONSTEP_W_LOAD_PARAMETER,
		CNCACTIONSTEP_SAVE_PARAMTER,
		CNCACTIONSTEP_W_SAVE_PARAMETER,
		CNCACTIONSTEP_START_SINGLESTEP,
		CNCACTIONSTEP_W_START_SINGLESTEP,
		CNCACTIONSTEP_STOP_SINGLESTEP,
		CNCACTIONSTEP_W_STOP_SINGLESTEP,
		CNCACTIONSTEP_SET_ZERO_TABLE,
		CNCACTIONSTEP_W_SET_ZERO_TABLE,
		CNCACTIONSTEP_SET_TOOL_TABLE,
		CNCACTIONSTEP_W_SET_TOOL_TABLE,
		CNCACTIONSTEP_SET_RPAR_TABLE,
		CNCACTIONSTEP_W_SET_RPAR_TABLE,
		CNCACTIONSTEP_SELECT_SUBJECT,
		CNCACTIONSTEP_LIMITS_INIT,
		CNCACTIONSTEP_W_LIMITS_INIT,
		CNCACTIONSTEP_DECODER_INIT,
		CNCACTIONSTEP_W_DECODER_INIT,
		CNCACTIONSTEP_AXES_INIT,
		CNCACTIONSTEP_W_AXES_INIT,
		CNCACTIONSTEP_CNC_PLC_INIT,
		CNCACTIONSTEP_W_CNC_PLC_INIT,
		CNCACTIONSTEP_CNC_SIM_ON,
		CNCACTIONSTEP_W_CNC_SIM_ON,
		CNCACTIONSTEP_CNC_SIM_OFF,
		CNCACTIONSTEP_W_CNC_SIM_OFF,
		CNCACTIONSTEP_SW_ON_RESTART,
		CNCACTIONSTEP_W_SW_ON_RESTART,
		CNCACTIONSTEP_SW_OFF_RESTART,
		CNCACTIONSTEP_W_SW_OFF_RESTART,
		CNCACTIONSTEP_RESTART_INFO,
		CNCACTIONSTEP_W_RESTART_INFO,
		CNCACTIONSTEP_SAVE_RESTART,
		CNCACTIONSTEP_W_SAVE_RESTART,
		CNCACTIONSTEP_SET_RESTART,
		CNCACTIONSTEP_W_SET_RESTART,
		CNCACTIONSTEP_RESTART_PROGRAM,
		CNCACTIONSTEP_W_RESTART_PROGRAM,
		CNCACTIONSTEP_SET_POS_MON_MODE,
		CNCACTIONSTEP_W_SET_POS_MON_MODE,
		CNCACTIONSTEP_CONTINUE_DECODER,
		CNCACTIONSTEP_W_CONTINUE_DECODER,
		CNCACTIONSTEP_LOAD_NCPROGRAM,
		CNCACTIONSTEP_W_LOAD_NCPROGRAM,
		CNCACTIONSTEP_UNLOAD_NCPROGRAM,
		CNCACTIONSTEP_W_UNLOAD_NCPROGRAM
		);
	CncAction_Type : 
		(
		CNCACTION_NO_ACTION,
		CNCACTION_GLOBAL_INIT,
		CNCACTION_START_NCPROGRAM,
		CNCACTION_START_NCBLOCK,
		CNCACTION_HALT,
		CNCACTION_CONTINUE,
		CNCACTION_STOP,
		CNCACTION_EMERGENCYSTOP,
		CNCACTION_ACKNOWLEDGE,
		CNCACTION_ERROR_TEXT,
		CNCACTION_ERROR_CHECK,
		CNCACTION_SAVE_PARAMETER,
		CNCACTION_LOAD_PARAMETER,
		CNCACTION_START_SINGLESTEP,
		CNCACTION_STOP_SINGLESTEP,
		CNCACTION_SET_ZERO_TABLE,
		CNCACTION_SET_TOOL_TABLE,
		CNCACTION_SET_RPAR_TABLE,
		CNCACTION_INIT_SUBJECT_PAR,
		CNCACTION_LIMITS_INIT,
		CNCACTION_DECODER_INIT,
		CNCACTION_AXES_INIT,
		CNCACTION_CNC_PLC_INIT,
		CNCACTION_CNC_SIMULATION_ON,
		CNCACTION_CNC_SIMULATION_OFF,
		CNCACTION_SW_ON_RESTART,
		CNCACTION_SW_OFF_RESTART,
		CNCACTION_RESTART_INFO,
		CNCACTION_SAVE_RESTART,
		CNCACTION_SET_RESTART,
		CNCACTION_RESTART_PROGRAM,
		CNCACTION_SET_POS_MON_MODE,
		CNCACTION_CONTINUE_DECODER,
		CNCACTION_LOAD_NCPROGRAM,
		CNCACTION_UNLOAD_NCPROGRAM
		);
END_TYPE
